// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const useCallback: (typeof import('react'))['useCallback'];
  const useContext: (typeof import('react'))['useContext'];
  const useEffect: (typeof import('react'))['useEffect'];
  const useHref: (typeof import('react-router'))['useHref'];
  const useInRouterContext: (typeof import('react-router'))['useInRouterContext'];
  const useLocation: (typeof import('react-router'))['useLocation'];
  const useMemo: (typeof import('react'))['useMemo'];
  const useNavigate: (typeof import('react-router'))['useNavigate'];
  const useNavigationType: (typeof import('react-router'))['useNavigationType'];
  const useOutlet: (typeof import('react-router'))['useOutlet'];
  const useOutletContext: (typeof import('react-router'))['useOutletContext'];
  const useParams: (typeof import('react-router'))['useParams'];
  const useReducer: (typeof import('react'))['useReducer'];
  const useRef: (typeof import('react'))['useRef'];
  const useResolvedPath: (typeof import('react-router'))['useResolvedPath'];
  const useRoutes: (typeof import('react-router'))['useRoutes'];
  const useState: (typeof import('react'))['useState'];
}
export {};
